package main

import (
	"flag"
	"fmt"
	"os"
	"ssx/client"
	"time"
)

const version = "1.0.1"

func main() {
	wsURI := flag.String("ws", "ws://127.0.0.1/api/ws", "server ws uri")
	socksPort := flag.Int("socks", 1086, "local socks proxy port")
	transporxyPort := flag.Int("transporxy", 0, "local tpc transparent proxy port")
	pacPort := flag.Int("pac", 0, "local pac server port")
	gfwlistURI := flag.String("gfwlist", "https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt", "gfwlist URI")
	dnsmasqconf := flag.Int("dnsmasqconf", 0, "create gfwlist.conf for DNSMASQ")
	printVersion := flag.Bool("version", false, "print version")
	flag.Parse()

	if *printVersion {
		fmt.Print(version)
		return
	}

	if *dnsmasqconf > 0 {
		s := &client.PACServer{
			GFWListURI: *gfwlistURI,
		}
		list, err := s.GFWList()
		if err != nil {
			fmt.Println("can not download gfwlist")
			os.Exit(1)
		}
		fmt.Printf("# dnsmasq rules generated by gfwlist\n# last updated on %s\n#\n\n", time.Now().Format("2006-01-02 15:04:05"))
		for host := range list {
			fmt.Printf("server=/.%s/127.0.0.1#%d\nipset=/.%s/gfwlist\n", host, *dnsmasqconf, host)
		}
		return
	}

	client.Run(*wsURI, uint16(*socksPort), uint16(*transporxyPort), uint16(*pacPort), *gfwlistURI)
}
